version: '3'
services:
  my-nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - mynet
    deploy:
      # replicas: 2
      resources:
        reservations:
          memory: 100m
        limits:
          memory: 300m
      restart_policy:
        condition: any
      # update_config:
      #   parallelism: 2
      #   delay: 10s

networks:
  mynet: